# Generated by Django 4.2.6 on 2023-11-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
